version: 0.2

phases:
  build:
    commands:
      - echo "Building the app"
      - ls
      - echo "Checking for 'Congratulations' in index.html"
      - grep "Congratulations" index.html
  post_build:
    commands:
      - echo "Post build phase"

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - scripts/stop_server
  discard-paths: no
